# docker-compose with the ManiaPlanet Dockerfile for Multiple Servers.
version: "3"
services:
    maniaplanet_mariadb:
        container_name: maniaplanet_mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: azerty  # default root => changed on first config mysql_secire_installation
        volumes:
            - ./mariadb/data:/var/lib/mysql
        expose: # visible only by the other containers (not the internet)
            - 3306 # Not mandatory (because exposed by the image) but more explicit to have the information here
    
    maniaplanet_pimserver7:
        container_name: maniaplanet_pimserver7
        build: .
        restart: always
        env_file:
            - dedicated_vars.pimserver7.env
        volumes:
            - ./UserData:/dedicated/UserData
            - ./Logs/pimserver7:/dedicated/Logs
        expose: # visible only by the other containers (not the internet)
            - 5007
        ports: # visible by everyone (especially the internet)
            - 2357:2357
            - 2357:2357/udp
            - 3457:3457
            - 3457:3457/udp

    maniaplanet_pimserver8:
        container_name: maniaplanet_pimserver8
        build: .
        restart: always
        env_file:
            dedicated_vars.pimserver8.env
        volumes:
            - ./UserData:/dedicated/UserData
            - ./Logs/pimserver8:/dedicated/Logs
        expose: # visible only by the other containers (not the internet)
            - 5008
        ports: # visible by everyone (especially the internet)
            - 2358:2358
            - 2358:2358/udp
            - 3458:3458
            - 3458:3458/udp

    maniaplanet_pimserver7_maniacontrol:
        container_name: maniaplanet_pimserver7_maniacontrol
        build: maniacontrol
        restart: always
        env_file: ./dedicated_vars.pimserver7.env
        depends_on:
            - maniaplanet_mariadb
            - maniaplanet_pimserver7
        volumes:
            - ./maniacontrol/configs:/maniacontrol/configs
            - ./maniacontrol/logs/pimserver7:/maniacontrol/logs

    maniaplanet_pimserver8_maniacontrol:
        container_name: maniaplanet_pimserver8_maniacontrol
        build: maniacontrol
        restart: always
        env_file: ./dedicated_vars.pimserver8.env
        depends_on:
            - maniaplanet_mariadb
            - maniaplanet_pimserver8
        volumes:
            - ./maniacontrol/configs:/maniacontrol/configs
            - ./maniacontrol/logs/pimserver8:/maniacontrol/logs

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: # visible by everyone (especially the internet)
            - 6080:80
        depends_on:
            - maniaplanet_mariadb
        environment:
            PMA_HOST: maniaplanet_mariadb
            PMA_PORT: 3306
