# docker-compose with the ManiaPlanet Dockerfile for Pim Servers.
version: "3"
services:
    maniaplanet_mariadb:
        container_name: maniaplanet_mariadb
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: azerty  # default root => changed on first config mysql_secire_installation
        volumes:
            - ./mariadb/data:/var/lib/mysql
        expose: # visible only by the other containers (not the internet)
            - 3306 # Not mandatory (because exposed by the image) but more explicit to have the information here
    
    my_server_01:
        container_name: my_server_01
        build: .
        restart: always
        env_file: ./dedicated_vars.my_server_01.env
        volumes:
            - ./UserData:/dedicated/UserData
            - ./Logs/my_server_01:/dedicated/Logs
        expose: # visible only by the other containers (not the internet)
            - 5001
        ports: # visible by everyone (especially the internet)
            - 2351:2351
            - 2351:2351/udp
            - 3451:3451
            - 3451:3451/udp

#    my_server_02:
#        container_name: my_server_02
#        build: .
#        restart: always
#        env_file: ./dedicated_vars.my_server_02.env
#        volumes:
#            - ./UserData:/dedicated/UserData
#            - ./Logs/my_server_02:/dedicated/Logs
#        expose: # visible only by the other containers (not the internet)
#            - 5002
#        ports: # visible by everyone (especially the internet)
#            - 2352:2352
#            - 2352:2352/udp
#            - 3452:3452
#            - 3452:3452/udp

    my_server_01_maniacontrol:
        container_name: my_server_01_maniacontrol
        build: maniacontrol
        restart: always
        env_file: ./dedicated_vars.my_server_01.env
        depends_on:
            - maniaplanet_mariadb
            - my_server_01
        volumes:
            - ./maniacontrol/configs:/maniacontrol/configs
            - ./maniacontrol/logs/my_server_01:/maniacontrol/logs

#    my_server_02_maniacontrol:
#        container_name: my_server_02_maniacontrol
#        build: maniacontrol
#        restart: always
#        env_file: ./dedicated_vars.my_server_02.env
#        depends_on:
#            - maniaplanet_mariadb
#            - my_server_02
#        volumes:
#            - ./maniacontrol/configs:/maniacontrol/configs
#            - ./maniacontrol/logs/my_server_02:/maniacontrol/logs

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: always
        ports: # visible by everyone (especially the internet)
            - 6080:80
        depends_on:
            - maniaplanet_mariadb
        environment:
            PMA_HOST: maniaplanet_mariadb
            PMA_PORT: 3306
