#!/bin/sh

echo "ManiaControl_multi.sh [INFO] - Start"
# Make sure we use defaults everywhere.
: ${SERVER_LOGIN:=dedicated_login}
: ${MANIACONTROL_CONFIG_FILE_FORCE_OVERWRITE:=1}
: ${DEDICATED_HOST:=maniaplanet_dedicated_login}
: ${XMLRPC_PORT:=5000}
: ${SERVER_PASSWORD:=dedicated_password}
: ${DEDICATED_MARIADB_HOST:=maniaplanet_mariadb}
: ${DEDICATED_MARIADB_PORT:=3306}
: ${DEDICATED_MARIADB_MANIACONTROL_USER:=maniacontrol}
: ${DEDICATED_MARIADB_MANIACONTROL_PASSWORD:=}
: ${DEDICATED_MARIADB_MANIACONTROL_DATABASE:=maniacontrol_db}
: ${MASTERADMIN_LOGIN:=}
: ${ADMIN_LOGIN_01:=}
: ${ADMIN_LOGIN_02:=}

MANIACONTROL_CONFIG_SOURCE_FILE_FULL="${PROJECT_DIR}/maniacontrol.config.default.xml"
MANIACONTROL_CONFIG_TARGET_FILE="maniacontrol.config.${SERVER_LOGIN}.xml"
MANIACONTROL_CONFIG_TARGET_FILE_FULL="${PROJECT_DIR}/configs/${MANIACONTROL_CONFIG_TARGET_FILE}"
if [[ -f ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} ]] && [[ ${MANIACONTROL_CONFIG_FILE_FORCE_OVERWRITE} -ne 1 ]]; then
    echo "=> File ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} existing but it should not be overwrited !"
elif [[ ! -f ${MANIACONTROL_CONFIG_SOURCE_FILE_FULL} ]]; then
    echo "=> ERROR : File ${MANIACONTROL_CONFIG_SOURCE_FILE_FULL} not existing !"
    exit 1
else
    if [[ ! -f ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} ]]; then
        echo "=> File ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} not existing : copy from ${MANIACONTROL_CONFIG_SOURCE_FILE_FULL}"
    fi
    cp ${MANIACONTROL_CONFIG_SOURCE_FILE_FULL} ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    echo "=> File ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} will be updated using env variable"
    sed -i "s|#DEDICATED_HOST#|${DEDICATED_HOST}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#XMLRPC_PORT#|${XMLRPC_PORT}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#SERVER_PASSWORD#|${SERVER_PASSWORD}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#DEDICATED_MARIADB_HOST#|${DEDICATED_MARIADB_HOST}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#DEDICATED_MARIADB_PORT#|${DEDICATED_MARIADB_PORT}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#DEDICATED_MARIADB_MANIACONTROL_USER#|${DEDICATED_MARIADB_MANIACONTROL_USER}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#DEDICATED_MARIADB_MANIACONTROL_PASSWORD#|${DEDICATED_MARIADB_MANIACONTROL_PASSWORD}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#DEDICATED_MARIADB_MANIACONTROL_DATABASE#|${DEDICATED_MARIADB_MANIACONTROL_DATABASE}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#MASTERADMIN_LOGIN#|${MASTERADMIN_LOGIN}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#ADMIN_LOGIN_01#|${ADMIN_LOGIN_01}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    sed -i "s|#ADMIN_LOGIN_02#|${ADMIN_LOGIN_02}|g" ${MANIACONTROL_CONFIG_TARGET_FILE_FULL}
    echo "=> File ${MANIACONTROL_CONFIG_TARGET_FILE_FULL} updated"
fi

# ITERATION_NUMBER=10
# NUMBER_OF_SECOND_PER_ITERATION=1
# for i in `seq 1 ${ITERATION_NUMBER}`;
# do
#     echo "ManiaControl_multi.sh [INFO] - Wait for 1 sec than server is open - ${i} / ${ITERATION_NUMBER}"
#     sleep ${NUMBER_OF_SECOND_PER_ITERATION}
# done

php ManiaControl.php -config=${MANIACONTROL_CONFIG_TARGET_FILE} >./logs/ManiaControl.log 2>&1
# echo $! > ./logs/ManiaControl.pid

echo "ManiaControl_multi.sh [INFO] - End"
